jd_reservation_index:
    path: /
    defaults:
        { _controller: JDLouvreBundle:Reservation:index, resaCode: null }

jd_reservation_startReservation:
    path: /reservation/
    defaults:
        { _controller: JDLouvreBundle:Reservation:startReservation, resaCode: null }

jd_reservation_startBillets:
    path: /billets/{id}/{resacode}
    defaults:
        _controller: JDLouvreBundle:Reservation:startBillets

jd_reservation_panier:
    path: /panier/
    defaults:
        _controller: JDLouvreBundle:Reservation:panier