services:
    jd_reservation.outilsreservation:
        class: JD\LouvreBundle\Services\OutilsReservation\OutilsReservation
        arguments:
            - "@doctrine.orm.entity_manager"
            - '@session'

    jd_reservation.outilsbillets:
        class: JD\LouvreBundle\Services\OutilsBillets\OutilsBillets
        arguments:
              - "@doctrine.orm.entity_manager"
              - '@session'

    jd_reservation.contraintBillets:
      class: JD\LouvreBundle\Contraintes\NbBillets\NbBilletsContraintValidator
      arguments: ["@doctrine.orm.entity_manager"]
      autowire: true
      tags:
          - { name: validator.constraint_validator }